# Generated by Django 5.0.9 on 2025-10-02 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Action performed', max_length=100)),
                ('entity', models.CharField(help_text='Entity type (study, signup, credit, etc.)', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_logs_entity_22e216_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for grant, negative for revoke', max_digits=4)),
                ('reason', models.TextField(blank=True, help_text='Explanation for this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_issued', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='studies.study')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant', '-created_at'], name='credit_tran_partici_e3f42a_idx'), models.Index(fields=['study', '-created_at'], name='credit_tran_study_i_d90aba_idx'), models.Index(fields=['course', '-created_at'], name='credit_tran_course__6a86b3_idx')],
            },
        ),
    ]
