# Generated by Django 5.0.9 on 2025-10-02 18:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Detailed study description shown to participants')),
                ('mode', models.CharField(choices=[('lab', 'In-Person Lab Study'), ('online', 'Online Study')], db_index=True, max_length=10)),
                ('credit_value', models.DecimalField(decimal_places=2, default=1.0, help_text='Research credits awarded upon completion', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Study is visible to participants')),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approval status')),
                ('eligibility', models.JSONField(blank=True, default=dict, help_text='Eligibility rules: age_min, age_max, languages, courses, excluded_studies')),
                ('consent_text', models.TextField(help_text='Consent form text participants must agree to')),
                ('external_link', models.URLField(blank=True, help_text='Survey/experiment URL for online studies')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Estimated duration')),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum total participants (leave blank for unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.ForeignKey(limit_choices_to={'role': 'researcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'db_table': 'studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1, help_text='Number of participants per timeslot', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, help_text='Lab room number, building, or Zoom link', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for researcher')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='studies.study')),
            ],
            options={
                'verbose_name': 'Timeslot',
                'verbose_name_plural': 'Timeslots',
                'db_table': 'timeslots',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('consent_text_version', models.TextField(help_text='Copy of consent text at time of signup')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_2h_sent', models.BooleanField(default=False)),
                ('participant_notes', models.TextField(blank=True, help_text='Notes from participant')),
                ('researcher_notes', models.TextField(blank=True, help_text='Private notes from researcher')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='studies.timeslot')),
            ],
            options={
                'verbose_name': 'Signup',
                'verbose_name_plural': 'Signups',
                'db_table': 'signups',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['mode', 'is_active'], name='studies_mode_3299a4_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['researcher', 'is_active'], name='studies_researc_607c98_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['study', 'starts_at'], name='timeslots_study_i_5576cd_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['starts_at', 'is_cancelled'], name='timeslots_starts__9521ce_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['participant', 'status'], name='signups_partici_bc8ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['timeslot', 'status'], name='signups_timeslo_affbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['status', 'booked_at'], name='signups_status_d2e7a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together={('timeslot', 'participant')},
        ),
    ]
