# Generated by Django 5.0.9 on 2025-10-17 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_analysis_plugin_study_bf_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='irb_approval_notes',
            field=models.TextField(blank=True, help_text='IRB reviewer notes and comments'),
        ),
        migrations.AddField(
            model_name='study',
            name='irb_approved_at',
            field=models.DateTimeField(blank=True, help_text='When IRB approval was granted', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='irb_approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved this study', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irb_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='irb_last_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Last IRB review date', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='irb_last_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Last person to review IRB status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irb_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
