# Generated by Django 5.0.9 on 2025-10-02 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescreenQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('boolean', 'Yes/No'), ('number', 'Number'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('text', 'Free Text')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for choice questions')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescreen Question',
                'verbose_name_plural': 'Prescreen Questions',
                'db_table': 'prescreen_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescreenResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text='Dictionary of {question_id: answer_value}')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescreen_response', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescreen Response',
                'verbose_name_plural': 'Prescreen Responses',
                'db_table': 'prescreen_responses',
            },
        ),
    ]
